revmatch_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: revmatch-project
      dataset: revmatch
      threads: 4
      keyfile: /opt/airflow/keys/gcp-key.json