version: 2

sources:
  - name: revmatch            # matches source('revmatch', ...)
    database: "{{ target.project }}"
    schema: "{{ target.schema }}"
    tables:
      - name: usage_events
      - name: billing_records
