version: '3'
x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: airflow/Dockerfile
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    AIRFLOW__LOGGING__LEVEL: INFO
    GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/keys/gcp-key.json
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/scripts:/opt/airflow/scripts
    - ./data:/opt/airflow/data
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./airflow/keys:/opt/airflow/keys
    - ./dbt:/opt/airflow/dbt                   
    - ./dbt/profiles.yml:/home/airflow/.dbt/profiles.yml
  user: "${AIRFLOW_UID}:${AIRFLOW_GID}"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  redis:
    image: redis:latest

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      - airflow-webserver

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    depends_on:
      - airflow-scheduler

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    depends_on:
      - airflow-worker

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "airflow db migrate &&
               airflow users create --username airflow --password airflow --firstname Arvil --lastname Dey --role Admin --email arvil@example.com"
    depends_on:
      - postgres
      - redis

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keys/gcp-key.json
    volumes:
      - ./api:/app
      - ./airflow/keys/gcp-key.json:/app/keys/gcp-key.json
    depends_on:
      - airflow-worker

  dashboard:
    build:
      context: ./dashboard
    ports:
      - "8501:8501"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keys/gcp-key.json
    volumes:
      - ./dashboard:/app
      - ./airflow/keys/gcp-key.json:/app/keys/gcp-key.json
    depends_on:
      - api

volumes:
  postgres-db-volume:
