version: 2

models:
  - name: stg_billing_records
    description: "Staging model that cleans billing_records data"
    columns:
      - name: tenant_id
        description: "Unique identifier for each tenant"
        tests: [not_null]
      - name: amount
        description: "Amount billed to the tenant"
        tests: [not_null]
      - name: billing_time
        description: "Time the billing was recorded"
        tests: [not_null]
